"""
Django settings for trading_backend project.

Generated by 'django-admin startproject' using Django 4.2.23.
"""

from pathlib import Path
from datetime import timedelta
import os  # (1) إضافة لاستخدام متغيرات البيئة
import dj_database_url  # (2) إضافة لاستخدام قاعدة بيانات PostgreSQL

BASE_DIR = Path(__file__).resolve().parent.parent

# (3) تعديل المفتاح السري لاستخدام متغيرات البيئة من Railway
# القيمة الافتراضية هنا هي المفتاح الجديد الذي ولدناه: bgg&r8*esu&2rgp(be=ayc1#l#9^b5nuy$-34xyom#ts_n+wdo
SECRET_KEY = os.environ.get('SECRET_KEY', 'bgg&r8*esu&2rgp(be=ayc1#l#9^b5nuy$-34xyom#ts_n+wdo')

# (4) تعديل وضع التصحيح لاستخدام متغيرات البيئة من Railway
# سيتم تعيينه على False بشكل افتراضي على Railway
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# (5) تعديل المضيفين المسموحين (ALLOWED_HOSTS)
# هذا يسمح لخادم Railway بالوصول إلى موقعك
# (5) تعديل المضيفين المسموحين (ALLOWED_HOSTS)
# هذا يسمح لخادم Railway بالوصول إلى موقعك
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trading_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trading_backend.wsgi.application'


# (6) تعديل قاعدة البيانات لاستخدام PostgreSQL على Railway
# سيتم قراءة DATABASE_URL من متغيرات بيئة Railway
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600
    )
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files
STATIC_URL = 'static/'


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django Rest Framework & JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}